### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by paxperscientiam** [adamdrake/harold#1]
Hey @adamdrake , `harold` is very cool; it's working great so far on macOS Mojave. Do you just run it from a home server or some cloud service?

Thanks.

EDIT: I have `harold` working nicely in screen on a remote server.

Wondering now if `harold` will ever be able to remove "likes" too. ty

**Comment by adamdrake** [comment]
Thank you for the feedback, @paxperscientiam!  I haven't had anyone else give feedback about removing likes in addition to the current removal capabilities, but it's definitely doable.

To answer your question, I've run the service on a local machine, on an EC2 instance, and I also have a modified version that can run on AWS Lambda.

If you want to add some capabilities to delete likes, feel free to do so and send a PR.

I'm glad `harold` has been helpful for you!

**Comment by paxperscientiam** [comment]
@adamdrake As for the remote services, running in screen has worked great except for the fact the screen sessions seem to die after some indeterminate amount of time.

Maybe it's because I'm using shared hosting. Do you run harold in a screen session on the EC2 instance? If so, have you experienced the same issue with sessions dying?

**Comment by adamdrake** [comment]
Historically I've used tmux and not screen, but they're basically the same.  I am not sure what provider you're using for your hosting/VPS, but I cannot recall having any issues in the past with AWS (EC2 or Lightsail) or Linode killing things running in tmux/screen.

**Comment by adamdrake** [comment]
@paxperscientiam In case you'd like to do the tweeting from a Lambda function to avoid issues with GNU screen, I set up a repo with the Lambda version of the random tweeting capability from Harold:  [feedtweeter-lambda](https://github.com/adamdrake/feedtweeter-lambda).
